# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8e9efdcd4f03db63931b517c6e9dc52cd46718db86854ef0272c492e5b3d76107cfdaf7cb5f6f2574cfcb391621a9a08d0bf41dd1f4f6cc8d7d4139772ec130
  facebook_app_id: 188844504785554
  facebook_app_secret: f3f7672ef3acdd99ded78c009c55fedc
  twitter_app_id: Mwj7cWOoEp9J0bVIzQQ446FQO
  twitter_app_secret: 6OOsJ33Zi6eOkHP0ULuEi8PqUJuTadjqJfIV17uKssj31izTtu

test:
  secret_key_base: 62c002bf0469418a2292138970215769408f140c37020d90d14a68969c495aa5b56578d3a923fae82cd60d88909722a45803d9055905e2e6a2fa7199010573cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
